baseurl = "https://aboutfreakingtime.netlify.com/"
languageCode = "en-us"
title = "A Hugo website"
theme = "hugo-lithium"
googleAnalytics = "UA-131462153-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/rstudio/blogdown"
    weight = 3
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/rstudio"
    weight = 4
[[menu.main]]
    name = "Miami Tings"
    url = "http://miamioh.edu/index.html"
    weight = 2
[[menu.main]]
    name = "Links"
    url = "Links/"
    weight = 1
[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "eritrea_logo.png"
    width = 50
    height = 50
    alt = "Logo"

