---
title: Housing Study
author: Aman Maru
date: '2019-01-04'
slug: blogs
categories: ['R']
tags: ["R Markdown", "plot"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

#Housing Data

This is a review of housing data I pulled from <https://www.kaggle.com/gpandi007/usa-housing-dataset/version/1>

#Lets start off by getting a brief summary on the housing data:
```{r sumry,echo=FALSE,warning=FALSE}
library(tidyverse)
housing <- read.csv('C:/Users/maruaz/Documents/Projects/R_blogdown_projects/newdefault/newdefault/static/post/housingtest.csv')
housing.filt = housing %>% select(Id:Neighborhood)
summary(housing.filt)

```

#Below you will see a beautiful bar chart
```{r}
ggplot(housing.filt) + geom_col(aes(Neighborhood,LotArea,fill=LotConfig)) + coord_flip()

```

#Housing Details

This graph compares the area of houses and the frontage (width) of houses by the lands shape
```{r point,echo=FALSE,warning=FALSE}
library(dplyr)
library(ggplot2)
library(ggthemes)
ggplot(housing.filt) + geom_point(aes(LotFrontage,LotArea,color=LotShape)) + theme_tufte()
```

#animatetest

```{r animated, echo=FALSE,warning=FALSE}
library(gganimate)
library(gapminder)
library(ggthemes)
a = head(gapminder,35)
options(scipen = 999)
ggplot(a) + geom_point(aes(gdpPercap,lifeExp,size=pop,colour=country))  + facet_wrap(~country) +
  transition_time(year) + labs(title = 'year: {frame_time}') + theme_bw()

```


---

#Files

```{r echo = FALSE} 
xfun::embed_file('C:/Users/maruaz/Documents/Projects/R_blogdown_projects/newdefault/newdefault/static/post/housingtest.csv',"Housing Dataset")
```

---


